dataset_path: ../../BuildSFTDataset/output/transformed_output.jsonl
deepspeed_config_path: null
wandb_project: decomposed_reasoning_sft
wandb_entity: null
seed: 42
num_train_epochs: 8
learning_rate: 1e-5
optim: adamw_torch
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1.0e-6
weight_decay: 0.1
max_seq_length: 8192
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 2
warmup_ratio: 0.03
eval_split_ratio: 0.05
save_total_limit: 8
save_only_model: true
