run_name: qwen3_8b_to_think_aimek4_b1_ga12
model_name_or_path: Qwen/Qwen3-8B
output_dir: /fs/scratch/PAA0201/ollieproudman/DecomposedReasoning/SFTTraining/outputs/qwen3_8b_to_think_aimek4_b1_ga12
base_config: base_sft.yaml
lm_eval: lm_eval_vllm_aime_k4.yaml
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
