run_name: qwen3_1p7b_to_think_aimek4_bs30_b2
model_name_or_path: Qwen/Qwen3-1.7B
output_dir: /fs/scratch/PAA0201/ollieproudman/DecomposedReasoning/SFTTraining/outputs/qwen3_1p7b_to_think_aimek4_bs30_b2
base_config: base_sft.yaml
lm_eval: lm_eval_vllm_aime_k4.yaml
per_device_train_batch_size: 2
gradient_accumulation_steps: 5
