
base_config: ../base_sft.yaml
run_name: smoke_test_run
model_name_or_path: allenai/Olmo-3-7B-Instruct
output_dir: /fs/scratch/PAA0201/ollieproudman/DecomposedReasoning/SFTTraining/outputs/smoke_test_run
num_train_epochs: 2
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
lm_eval: ../lm_eval_vllm.yaml
